from .add_function import add_function
from .map_test import get_lengths
from .inheritance import Student
from .is_prime import is_prime
from .person_class import Person
from .person_class_self import Person
from .protected_class import ProtectedAttributes
from .temprature import Temperature
from .recursive import tri_recursion