# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Manual Python Testing 

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up multiple python versions
      uses: actions/setup-python@v4
      with:
        python-version: |
          3.7
          3.8
          3.9
          3.10
          3.11
          3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: |
        tox -p all
    - name: Test across versions
      run: |
        pip install pandas
        python3 hash_compare.py
    - name: Uploade to github
      uses: actions/upload-artifact@v4
      with:
        name: Artifact - ${{ matrix.os }}
        path: logs/*
        overwrite: true

